name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - &uv-install
        name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - &uv-python
        name: Set up Python
        run: uv python install
      - &uv-sync
        name: Install dependencies
        run: uv sync --all-packages --all-extras

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - name: Check formatting with ruff
        run: uv run ruff format --check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - name: Run typecheck with pyrefly
        run: uv run pyrefly check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - name: Run lint with ruff
        run: uv run ruff check

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - name: Run CLI with help flag
        run: uv run tq-oracle --help

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - run: uv run pytest

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - run: uv run pytest --run-integration

  live-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *uv-install
      - *uv-python
      - *uv-sync
      - name: Run against eth test vault
        run: |
          uv run tq-oracle --network mainnet \
                           --ignore-empty-vault \
                           --ignore-timeout-check \
                           --ignore-active-proposal-check \
                           --log-level debug \
                           --vault-rpc ${{ secrets.ETH_RPC }} \
                             0xDbC81B33A23375A90c8Ba4039d5738CB6f56fE8d
